version: '2'
services:
  vulndb:
    image: mongo
    container_name: vulndb
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
  dagda:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: dagda
    ports:
      - "5000:5000"
    environment:
      - VULNDB_HOST=vulndb
    links:
        - vulndb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp:/tmp:ro
      - ./dagda:/opt/app
